window.pdfJobsData = [
  {
    "id": 1000,
    "title": "Software Engineer III \u2013 Brackenfell, Cape Town",
    "company": "Shoprite",
    "location": "Cape Town",
    "salary": "Negotiable",
    "description": "o\nSoftware Engineer III \u2013 Brackenfell, Cape Town\nClosing Date:  13 July 2026 Reference Number:  SHO260629 -9 Job Type:  Full-\nTime\nAbout the Role  We are seeking an experienced Software Engineer III  to take the\nlead in designing, developing, and supporting complex enterprise applications. This\nrole involves working closely with system designers to deliver innovative, sustainable\nsolutions while mentoring junior engineers and ensuring high standards o f technical\nquality.\nYou\u2019ll be responsible for guiding projects through the full software development\nlifecycle, applying advanced expertise in system analysis, architecture, and\nintegration. If you thrive in solving complex problems, driving technical excellence,\nand building  high-performing teams, this opportunity is for you.\nKey Responsibilities\n\u2022 Lead the design, development, and implementation of enterprise -scale\napplications\n\u2022 Translate business requirements into robust technical solutions and\narchitectures\n\u2022 Conduct system analysis and oversee work delivered by junior engineers\n\u2022 Write clean, scalable code and enforce coding standards through reviews and\nQA\n\u2022 Guide best practices in testing, documentation, and solution delivery\n\u2022 Support and enhance existing systems while troubleshooting complex issues\n\u2022 Drive adherence to organisational frameworks, Agile methodologies, and\nDevOps practices\n\u2022 Mentor and coordinate Software Engineer I and II team members\nQualifications\n\u2022 Diploma/Degree in Information Systems or Computer Science (preferred)\n\u2022 Strong performance in IKM assessments (Development & Design)\n\u2022 Agile Foundation and Security (OWASP Top 10) training completed\n\u2022 Advanced certification in programming languages or solution design\n\u2022 Strong Java skills (essential); IBM ACE/CP4i exposure (preferred)\n\u2022 Formal leadership training advantageous\nExperience\n\u2022 5+ years as a Software Engineer/Analyst Programmer (essential)\n\u2022 Proven track record on complex SDLC projects\n\u2022 Expertise in .NET, .NET Core, and testing methodologies\n\u2022 Strong background in system integration, database design (T -SQL), and\nNoSQL (advantageous)\n\u2022 UI/UX design principles, SOLID, and OOP experience\n\u2022 Agile and DevOps project delivery experience\n\u2022 Retail industry exposure (essential)\nKnowledge & Skills\n\u2022 Expert knowledge of GIT/TFS, application architecture, and web services\n(SOAP/REST)\n\u2022 Strong UML skills (sequence/class diagrams)\n\u2022 Networking and security principles\n\u2022 Agile/SCRUM methodologies\n\u2022 Automation (unit testing, deployment)\n\u2022 Microservices architecture (desirable)\nFor more info/Applicationg o here:\nhttps://shoprite.erecruit.co/candidateapp/Jobs/View/SHO260629 -9",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@shoprite.co.za",
    "image": "pdf_images/1_Image33.jpg",
    "applyUrl": "https://shoprite.erecruit.co/candidateapp/Jobs/View/SHO260629"
  },
  {
    "id": 1001,
    "title": "Business Analyst III \u2013 Brackenfell, Cape Town",
    "company": "Shoprite",
    "location": "Cape Town",
    "salary": "Negotiable",
    "description": "Business Analyst III \u2013 Brackenfell, Cape Town\nClosing Date:  17 July 2026 Reference:  SHO260515 -3\nWe\u2019re looking for an experienced Business Analyst III  to join our IT team. This\npermanent role focuses on shaping competitive business processes, analysing\nrequirements, and delivering solutions that drive long -term value.\nWhat you\u2019ll do:\n\u2022 Analyse business needs, processes, and systems to identify improvements.\n\u2022 Collaborate with stakeholders to define requirements and recommend\nsolutions.\n\u2022 Lead workshops, mentor junior analysts, and influence decision -making.\n\u2022 Ensure data quality, reporting accuracy, and cost -effective solutions.\n\u2022 Drive change management, risk mitigation, and solution validation.\nWhat we\u2019re looking for:\n\u2022 Degree/Diploma in IT or related field (essential).\n\u2022 Advanced Business Analysis certification (preferred).\n\u2022 5+ years\u2019 BA experience with strong technical background.\n\u2022 Solid knowledge of SDLC, agile methods, and process modelling.\n\u2022 Strong IT skills; SAP exposure is a plus.\nWhy join us:  You\u2019ll play a key role in high -profile, cross -domain projects, helping\nshape solutions that benefit both the business and its customers.\nFor more info/ Application go  here:\nhttps://shoprite.erecruit.co/candidateapp/Jobs/View/SHO260515 -3",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@shoprite.co.za",
    "image": "pdf_images/4_Image42.jpg",
    "applyUrl": "https://shoprite.erecruit.co/candidateapp/Jobs/View/SHO260515"
  },
  {
    "id": 1002,
    "title": "Data Center Engineering Team Lead \u2013 Brackenfell, Cape Town",
    "company": "PDF Extract",
    "location": "Cape Town",
    "salary": "Negotiable",
    "description": "Data Center Engineering Team Lead \u2013 Brackenfell, Cape Town\nClosing Date:  13 July 2026 Reference:  SHO260629 -10\nWe\u2019re seeking a Data Center Engineering Team Lead  to design, optimise, and\nmanage infrastructure across leased environments. This full -time role ensures\nresilience, efficiency, and alignment with business needs while guiding a team and\nengaging with vendors.\nKey Responsibilities:\n\u2022 Analyse and improve compute, storage, virtualisation, and Unix platforms.\n\u2022 Monitor system health, capacity, and performance.\n\u2022 Lead and support engineering teams, resolving complex issues.\n\u2022 Oversee backup, recovery, and disaster readiness.\n\u2022 Collaborate with stakeholders to deliver scalable solutions.\n\u2022 Manage vendor relationships and drive cost optimisation.\nRequirements:\n\u2022 Relevant IT qualification.\n\u2022 5+ years\u2019 experience in data centre engineering/operations.\n\u2022 Strong background in virtualisation, storage, Unix/Linux, and backup\ntechnologies.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@pdfextract.co.za",
    "image": "pdf_images/5_Image45.jpg",
    "applyUrl": "https://shoprite.erecruit.co/candidateapp/Jobs/View/SHO260629-10"
  },
  {
    "id": 1003,
    "title": "General Worker \u2013 Darling",
    "company": "Shoprite",
    "location": "Darling, Western",
    "salary": "Negotiable",
    "description": "\u2022 Vendor management experience (beneficial).\n\u2022 2+ years in a leadership role (advantageous).\nPreferred Skills:\n\u2022 Exposure to leased data centre environments.\n\u2022 Knowledge of infrastructure optimisation practices.\nFor more info/ Apply here:\nhttps://shoprite.erecruit.co/candidateapp/Jobs/View/SHO260629 -10\nGeneral Worker \u2013 Darling\nClosing Date:  31 July 2026 Reference:  TRU260702 -13 Location:  Darling, Western\nCape\nDarling Manufacturers, in partnership with Truworths , is looking for a General\nWorker  on a temporary contract. The role focuses on keeping the workplace safe\nand clean, performing light maintenance, and ensuring machinery is well maintained.\nKey Responsibilities:\n\u2022 Maintain a clean and safe work environment.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@shoprite.co.za",
    "image": "pdf_images/6_Image49.jpg",
    "applyUrl": "https://shoprite.erecruit.co/candidateapp/Jobs/View/SHO260629"
  },
  {
    "id": 1004,
    "title": "Line Feeder \u2013 Darling",
    "company": "Truworths",
    "location": "Darling, Western",
    "salary": "Negotiable",
    "description": "\u2022 Perform basic maintenance tasks (e.g., changing light bulbs).\n\u2022 Keep machinery and equipment clean and in good condition.\nRequirements:\n\u2022 Previous experience as a General Worker.\nCompetencies:  Communication skills, teamwork, attention to detail, and reliability.\nFor more info/ application go here:\nhttps://truworths.erecruit.co/candidateapp/Jobs/View/TRU260702 -\n13https://truworths.erecruit.co/candidateapp/Jobs/View/TRU260702 -13\nLine Feeder \u2013 Darling\nClosing Date:  31 July 2026 Reference:  TRU260702 -23 Location:  Darling, Western\nCape\nDarling Manufacturers, in partnership with Truworths , is seeking a Line Feeder  on a\ntemporary contract. The role involves preparing and feeding fabric into production\nprocesses, positioning rolls, loading materials, and supporting the team to keep\nworkflow smooth and safe.\nKey Responsibilities:\n\u2022 Position cloth trucks at the feed end of machines.\n\u2022 Mount rolls of fabric onto brackets.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@truworths.co.za",
    "image": "pdf_images/7_Image54.jpg",
    "applyUrl": "https://truworths.erecruit.co/candidateapp/Jobs/View/TRU260702"
  },
  {
    "id": 1005,
    "title": "Sew fabric leaders using a portable sewing machine.",
    "company": "Truworths",
    "location": "Darling, Western",
    "salary": "Negotiable",
    "description": "\u2022 Sew fabric leaders using a portable sewing machine.\nRequirements:\n\u2022 Previous line feeder experience preferred.\nCompetencies:  Strong communication, teamwork, attention to detail, and reliability.\nFor more info/ application go here:\nhttps://truworths.erecruit.co/candidateapp/Jobs/View/TRU260702 -23\nSenior Supervisor \u2013 Darling\nClosing Date:  31 July 2026 Reference:  TRU260703 -1 Location:  Darling, Western\nCape\nDarling Manufacturers, in partnership with Truworths , is seeking a Senior\nSupervisor  to lead production teams and ensure efficiency, quality, and safety on\nthe clothing manufacturing floor. This permanent role focuses on balancing\nworkloads, enforcing standards, and driving daily production targets.\nKey Responsibilities:\n\u2022 Supervise operators and manage production lines.\n\u2022 Balance workloads and monitor efficiency.\n\u2022 Support line changeovers and resolve production issues.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@truworths.co.za",
    "image": "pdf_images/8_Image58.jpg",
    "applyUrl": "https://truworths.erecruit.co/candidateapp/Jobs/View/TRU260702"
  },
  {
    "id": 1006,
    "title": "Store Designer \u2013 Cape Town",
    "company": "Truworths",
    "location": "Western Cape,",
    "salary": "Negotiable",
    "description": "\u2022 Ensure garments meet Truworths\u2019 quality standards.\n\u2022 Contribute to pre -production meetings and planning.\nRequirements:\n\u2022 Matric qualification.\n\u2022 10+ years\u2019 senior -level clothing production experience.\n\u2022 Diploma in Clothing Production/Management (advantageous).\nCompetencies:\n\u2022 Strong garment construction knowledge.\n\u2022 Proven leadership and problem -solving skills.\n\u2022 Ability to monitor targets and manage production plans.\n\u2022 Quality -focused mindset with a can -do attitude.\n\u2022 Excellent communication and teamwork skills.\nFor more info rmation/ application go here:\nhttps://truworths.erecruit.co/candidateapp/Jobs/View/TRU260703 -1\nStore Designer \u2013 Cape Town\nClosing Date:  14 August 2026 Reference:  TRU250820 -9 Location:  Western Cape,\nSouth Africa\nJoin Truworths , South Africa\u2019s leading fashion retailer, and be part of a creative\nteam shaping the future of retail spaces. We\u2019re looking for a Store Designer  to\ndevelop innovative layouts and design solutions that reflect our brand\u2019s style and\nenhance the customer experience.\nKey Responsibilities:\n\u2022 Design store layouts and floor plans aligned with brand identity and\noperational needs.\n\u2022 Collaborate with internal teams and external partners to ensure cohesive\nexecution.\n\u2022 Create detailed 2D/3D visualisations using AutoCAD, SketchUp, and related\ntools.\n\u2022 Optimise space planning and customer flow to support sales.\n\u2022 Select materials, finishes, and fixtures within budget and design vision.\n\u2022 Review completed stores and recommend design improvements.\nRequirements:\n\u2022 Diploma or Degree in Interior Design, Architecture, or related field.\n\u2022 Minimum 5 years\u2019 experience in retail or commercial design.\n\u2022 Proficiency in AutoCAD, SketchUp, and Adobe Suite.\n\u2022 Strong creativity, attention to detail, and project management skills.\nCompetencies:  Creative, detail -oriented, and solutions -focused. Thrives in a\nfast-paced environment, passionate about retail innovation, and collaborative by\nnature.\nFor more information/ application go here:\nhttps://truworths.erecruit.co/candidateapp/Jobs/View/TRU250820 -9",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@truworths.co.za",
    "image": "pdf_images/9_Image62.jpg",
    "applyUrl": "https://truworths.erecruit.co/candidateapp/Jobs/View/TRU260703"
  },
  {
    "id": 1007,
    "title": "Cashier \u2013 Cape Gate",
    "company": "Dis-Chem",
    "location": "Cape Gate, Western Cape Division:  Retail",
    "salary": "Negotiable",
    "description": "Cashier \u2013 Cape Gate\nClosing Date:  16 July 2026  Location:  Cape Gate, Western Cape Division:  Retail\nIndustry:  FMCG Experience Level:  Entry\nDis-Chem Pharmacies  is looking for an experienced Cashier  to join the team at our\nCape Gate store. You\u2019ll deliver excellent customer service at checkout, ensure\naccurate transactions, and maintain a secure, efficient point -of-sale environment.\nKey Responsibilities:\n\u2022 Process customer purchases and payments accurately.\n\u2022 Maintain professionalism and uphold Dis -Chem\u2019s service standards.\n\u2022 Handle returns, exchanges, and loyalty card transactions.\n\u2022 Ensure cash safety and compliance with company procedures.\n\u2022 Report customer feedback and assist with queries.\nRequirements:\n\u2022 Grade 12 / Matric.\n\u2022 Minimum 6 months\u2019 cashier or till operation experience.\n\u2022 Computer literacy (MS Office).\n\u2022 Strong numerical and communication skills.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@dis-chem.co.za",
    "image": "pdf_images/11_Image68.jpg",
    "applyUrl": "https://retail.simplify.hr/Vacancy/192173"
  },
  {
    "id": 1008,
    "title": "Beauty Therapist \u2013 Meadowdale Salon (Germiston)",
    "company": "Dis-Chem",
    "location": "Germiston",
    "salary": "Negotiable",
    "description": "\u2022 Willingness to work retail hours.\nCompetencies:  Accuracy, attention to detail, honesty, time management, customer\nfocus, and problem -solving.\nBenefits:  Market -related salary, medical aid, provident fund, and staff account.\nFor more information/ application go here: https://retail.simplify.hr/Vacancy/192173\nBeauty Therapist \u2013 Meadowdale Salon (Germiston)\nClosing Date:  15 July 2026  Division:  Retail Industry:  Retail Experience Level:\nMid-Senior\nDis-Chem Pharmacies  is looking for an experienced Beauty Therapist  to join the\nteam at our Meadowdale Salon in Germiston. You\u2019ll deliver exceptional skincare and\nbody treatments, promote salon services, and ensure every client enjoys a\nworld -class beauty experience.\nKey Responsibilities:\n\u2022 Perform facials, waxing, massages, manicures, and pedicures according to\nDis-Chem standards.\n\u2022 Provide professional client care and maintain strong customer relationships.\n\u2022 Manage stock levels and ensure equipment is clean and operational.\n\u2022 Stay updated on new products, treatments, and techniques.\n\u2022 Report and respond to customer feedback and queries.\nRequirements:\n\u2022 Grade 12 / Matric.\n\u2022 2-year Certificate or Diploma in Beauty Therapy (3 -year qualification\nadvantageous).\n\u2022 Minimum 12 months\u2019 experience in a professional salon (3 years preferred).\n\u2022 Computer literacy and sound numerical skills.\n\u2022 Willingness to work retail hours.\nCompetencies:\n\u2022 Strong knowledge of skin anatomy and treatment contraindications.\n\u2022 Excellent communication and customer -service skills.\n\u2022 Team -oriented, target -driven, and detail -focused.\n\u2022 Experience with advanced treatments (laser, microdermabrasion, slimming,\nspray tan) advantageous.\nBenefits:  Market -related salary, medical aid, provident fund, and staff account.\nFor more information/ application go here: https://retail.simplify.hr/Vacancy/165860",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@dis-chem.co.za",
    "image": "pdf_images/12_Image72.jpg",
    "applyUrl": "https://retail.simplify.hr/Vacancy/192173"
  },
  {
    "id": 1009,
    "title": "FP&A Analyst \u2013 Studio 88",
    "company": "Studio 88",
    "location": "Head Office, South Africa Department:  Finance Reports To:  Head of",
    "salary": "Negotiable",
    "description": "FP&A Analyst \u2013 Studio 88\nLocation:  Head Office, South Africa Department:  Finance Reports To:  Head of\nFinance Employment Type:  Permanent Qualification:  CA(SA) \u2013 mandatory\nExperience:  1\u20132 years post -articles\nAbout the Role  Studio 88 is seeking a high -calibre FP&A Analyst  to support\nplanning, forecasting, budgeting, and analytical reporting across a retail network of\nover 1,000 stores and a growing online presence. This role demands strong financial\nmodelling, commercial insight, and the ability to translate complex data i nto\nactionable business intelligence.\nKey Responsibilities\n\u2022 Build and maintain dynamic financial models for trading, margin, cost, and\nworking capital.\n\u2022 Lead monthly forecasting and annual budgeting processes.\n\u2022 Deliver variance analyses and management commentary.\n\u2022 Develop Qlik Sense dashboards and BI reports for real -time performance\ntracking.\n\u2022 Conduct ad hoc analyses on profitability, cost attribution, and store\nperformance.\n\u2022 Support month -end close, audit preparation, and process improvement\ninitiatives.\nRequirements\n\u2022 CA(SA) qualification (registered with SAICA).\n\u2022 Completed SAICA -accredited articles (Big 4 or mid -tier firm).\n\u2022 1\u20132 years post -articles experience in FP&A, commercial finance, or business\npartnering.\n\u2022 Advanced Excel and strong financial modelling skills.\n\u2022 Exposure to BI tools (Qlik Sense, Power BI, Tableau) preferred.\n\u2022 Solid understanding of IFRS, management accounting, and forecasting\nmethodologies.\nCompetencies & Attributes\n\u2022 Intellectual curiosity and analytical strength.\n\u2022 Commercial acumen and business awareness.\n\u2022 Ownership, integrity, and attention to detail.\n\u2022 Strong communication and presentation skills.\n\u2022 Resilience under pressure and a growth mindset.\nFor more info or to apply go here: https://careers88.co.za/job/2 -financial -planning -\nanalysis -fpa-analyst/",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@studio88.co.za",
    "image": "pdf_images/14_Image78.jpg",
    "applyUrl": "https://careers88.co.za/job/2"
  },
  {
    "id": 1010,
    "title": "Sales Assistant \u2013 Pretoria, Gauteng",
    "company": "Studio 88",
    "location": "Studio 88 Group of",
    "salary": "Negotiable",
    "description": "Sales Assistant \u2013 Pretoria, Gauteng\nDivision:  Operations Reports To:  Store Manager Location:  Studio 88 Group of\nCompanies Experience Level:  Entry to Intermediate\nPosition Overview  As a Sales Assistant  at Studio 88 Group of Companies , you\u2019ll\nplay a vital role in delivering exceptional customer service, driving sales, and\nmaintaining store presentation standards. You\u2019ll assist customers in finding products,\nprocess transactions efficiently, and ensure every shopper enjoys a positive\nexperience.\nMinimum Qualifications\n\u2022 Grade 12 or equivalent.\n\u2022 1\u20132 years\u2019 experience in a sales environment (retail clothing experience\nadvantageous).\n\u2022 Proven ability to meet or exceed sales targets.\n\u2022 Experience supporting store operations \u2014 restocking, folding, organizing\napparel, and maintaining cleanliness.\n\u2022 Proficiency in cash handling, POS systems, and transaction processing.\nKey Responsibilities",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@studio88.co.za",
    "image": "pdf_images/16_Image85.jpg",
    "applyUrl": "https://careers88.co.za/job/pretoria-south-africa-4-sales-assistant/"
  },
  {
    "id": 1011,
    "title": "Retail Shop Assistant \u2013 Toys R Us / Babies R Us",
    "company": "Toys R Us / Babies R Us",
    "location": "Pretoria",
    "salary": "Negotiable",
    "description": "\u2022 Provide friendly, professional customer service and resolve queries effectively.\n\u2022 Assist customers with product selection, sizing, and styling advice.\n\u2022 Upsell and cross -sell complementary products.\n\u2022 Maintain visual merchandising standards and store displays.\n\u2022 Support inventory control through stock organization and spot checks.\n\u2022 Ensure accurate cash handling and transaction processing.\n\u2022 Contribute to a clean, organized, and welcoming store environment.\nSkills & Attributes\n\u2022 Strong interpersonal and communication skills.\n\u2022 Customer -focused with a positive, professional attitude.\n\u2022 Team player with good time management and reliability.\n\u2022 Self-motivated and able to work under pressure.\n\u2022 Knowledge of clothing brands, sizes, and fashion trends.\nFor more info or to apply go here: https://careers88.co.za/job/pretoria -south -africa -4-\nsales -assistant/\nRetail Shop Assistant \u2013 Toys R Us / Babies R Us\nClosing Date:  1 August 2026 Department:  Sales Industry:  Retail Experience\nLevel:  Entry\nIntroduction  Step into the Toys R Us world of AWWWESOME , where imagination\nruns free! With over 60 stores across South Africa, Namibia, Botswana, and Zambia\n\u2014 plus our new online store \u2014 we\u2019re committed to delivering a WOW shopping\nexperience for customers of all ages. We\u2019re looking for a dynamic Retail Shop\nAssistant  to join our team and help us create unforgettable moments.\nJob Purpose  Maximise sales by delivering exceptional customer service and\nensuring every shopper enjoys a WOW experience.\nKey Skills Needed\n\u2022 Sales -driven and motivated to meet targets.\n\u2022 Excellent customer service and communication skills.\n\u2022 Tenacious, confident, and enthusiastic.\n\u2022 Strong merchandising and product presentation skills.\nKey Responsibilities\n\u2022 Provide friendly, professional service to every customer.\n\u2022 Assist with product selection, demonstrations, and advice.\n\u2022 Drive sales, including add -on products and services.\n\u2022 Ensure goods are correctly priced, displayed, and promotions executed.\n\u2022 Maintain store housekeeping and merchandising standards.\n\u2022 Report fast and slow sellers to the Store Manager.\n\u2022 Participate in stock counts and minimise losses.\n\u2022 Protect company assets and manage expenses responsibly.\nEntry Requirements\n\u2022 Matric Certificate.\n\u2022 Minimum 6 months\u2019 retail experience.\n\u2022 Reliable transport and ability to work shifts.\nGeneral Duties\n\u2022 Undertake training, appraisals, and personal development reviews.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@toysrusbabiesrus.co.za",
    "image": "pdf_images/17_Image90.jpg",
    "applyUrl": "https://careers88.co.za/job/pretoria"
  },
  {
    "id": 1012,
    "title": "Compliance Auditor \u2013 Retail Operations",
    "company": "PDF Extract",
    "location": "South Africa",
    "salary": "Negotiable",
    "description": "\u2022 Maintain confidentiality and comply with SOPs.\n\u2022 Support new technologies and methods introduced by management.\nFor more or to apply: https://toysruscareers.simplify.hr/Vacancy/191961\nCompliance Auditor \u2013 Retail Operations\nClosing Date:  6 August 2026 Department:  Compliance Industry:  Retail\nExperience Level:  Associate\nJob Purpose  To strengthen operations by applying a systematic, disciplined\napproach to auditing and reporting on the effectiveness of risk management, internal\ncontrols, and governance processes.\nKey Skills Needed\n\u2022 Strong analytical and problem -solving ability.\n\u2022 Excellent documentation and communication skills.\n\u2022 Ability to manage large datasets and compile detailed reports.\n\u2022 Knowledge of auditing standards and SOPs.\n\u2022 Adaptability, multitasking, and resilience under pressure.\n\u2022 Meticulous attention to detail and accuracy.\n\u2022 Strong interpersonal skills and ability to work independently or in a team.\nKey Responsibilities\n\u2022 Perform full audit cycles: methodology, fieldwork, and reporting.\n\u2022 Provide independent assurance on risk management, governance, and\ncontrols.\n\u2022 Rate compliance against SOPs and maintain objectivity.\n\u2022 Investigate fraud, theft, waste, or embezzlement.\n\u2022 Conduct risk -based audits across admin, inventory, sales, and seasonal\nprocesses.\n\u2022 Identify risks proactively and recommend practical solutions.\n\u2022 Evaluate governance and control effectiveness across departments.\n\u2022 Analyze root causes of audit findings and ensure corrective action.\n\u2022 Prepare high -quality audit reports and communicate findings.\n\u2022 Travel to audit sites as required.\nEntry Requirements\n\u2022 Relevant auditing or compliance qualification.\n\u2022 Associate -level experience in compliance or auditing.\n\u2022 Strong computer literacy and report -writing skills.\nBehavioral Attributes\n\u2022 Professional, confident, and self -motivated.\n\u2022 Detail -oriented with integrity and objectivity.\n\u2022 Team player with strong accountability.\n\u2022 Able to work under pressure and meet deadlines.\nFor more information or to apply: https://toysruscareers.simplify.hr/Vacancy/192665",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@pdfextract.co.za",
    "image": "pdf_images/19_Image90.jpg",
    "applyUrl": "https://toysruscareers.simplify.hr/Vacancy/191961"
  },
  {
    "id": 1013,
    "title": "Retail Shop Assistant \u2013 Toys R Us / Babies R Us",
    "company": "Toys R Us / Babies R Us",
    "location": "South Africa",
    "salary": "Negotiable",
    "description": "Retail Shop Assistant \u2013 Toys R Us / Babies R Us\nClosing Date:  Not specified Department:  Sales Industry:  Retail Experience\nLevel:  Entry\nIntroduction  Step into the Toys R Us world of AWWWESOME , where imagination\nruns free! With over 60 stores across South Africa, Namibia, Botswana, and Zambia\n\u2014 plus our new online store \u2014 we\u2019re committed to delivering a WOW shopping\nexperience for customers of all ages. We\u2019re looking for a passionate Retail Shop\nAssistant  to join our team and help us create unforgettable moments.\nJob Purpose  Maximise sales by delivering exceptional customer service and\nensuring every shopper enjoys a WOW experience.\nKey Skills Needed\n\u2022 Sales -driven and motivated to meet targets.\n\u2022 Excellent customer service and communication skills.\n\u2022 Tenacious, confident, and enthusiastic.\n\u2022 Strong merchandising and product presentation skills.\nKey Responsibilities\n\u2022 Provide friendly, professional service to every customer.\n\u2022 Assist with product selection, demonstrations, and advice.\n\u2022 Drive sales, including add -on products and services.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@toysrusbabiesrus.co.za",
    "image": "pdf_images/21_Image101.jpg",
    "applyUrl": ""
  },
  {
    "id": 1014,
    "title": "Report fast and slow sellers to the Store Manager.",
    "company": "Capitec",
    "location": "Johannesburg, South Africa Company:  Capitec Bank Ltd Closing Date:",
    "salary": "Negotiable",
    "description": "\u2022 Ensure goods are correctly priced, displayed, and promotions executed.\n\u2022 Maintain store housekeeping and merchandising standards.\n\u2022 Report fast and slow sellers to the Store Manager.\n\u2022 Participate in stock counts and minimise losses.\n\u2022 Protect company assets and manage expenses responsibly.\nEntry Requirements\n\u2022 Matric Certificate.\n\u2022 Minimum 6 months\u2019 retail experience.\n\u2022 Reliable transport and ability to work shifts.\nGeneral Duties\n\u2022 Undertake training, appraisals, and personal development reviews.\n\u2022 Maintain confidentiality and comply with SOPs.\n\u2022 Support new technologies and methods introduced by management.\nFor more information or to apply : https://toysruscareers.simplify.hr/Vacancy/181165\nTeam Leader: Operational Analytics (Operations Delivery)\nLocation:  Johannesburg, South Africa Company:  Capitec Bank Ltd Closing Date:\n10 July 2026 Department:  Operations Delivery Experience Level:  Mid-Senior\nPurpose Statement  Lead a team of Business Analysts to analyse business\nprocesses, identify improvement opportunities, and deliver sustainable solutions that\nenhance operational efficiency, effectiveness, and client outcomes. This role drives\ncontinuous improvement, enables  business transformation, and ensures operational\nprocesses align with strategic objectives.\nKey Responsibilities\n\u2022 Lead and develop a team of Business Analysts.\n\u2022 Drive continuous improvement and operational optimisation initiatives.\n\u2022 Facilitate process redesign and operational excellence.\n\u2022 Translate business challenges into practical, sustainable solutions.\n\u2022 Build strong stakeholder relationships across business areas.\n\u2022 Foster innovation and a culture of continuous improvement.\nExperience Required\n\u2022 3\u20135 years\u2019 experience leading Business Analysts, Process Analysts, or\nContinuous Improvement Specialists.\n\u2022 Proven track record in process optimisation and business improvement.\n\u2022 Experience in requirements gathering, solution design, and workshop\nfacilitation.\n\u2022 Exposure to Lean, Agile, Six Sigma, or similar methodologies.\n\u2022 Experience mentoring and developing analytical teams.\nQualifications\n\u2022 Minimum: Grade 12 National Certificate and relevant tertiary qualification in\nBusiness Administration.\n\u2022 Preferred: Bachelor\u2019s Degree and/or professional qualification in Business\nAnalysis or Data Analysis.\nKnowledge\n\u2022 Team leadership and operations management practices.\n\u2022 Business analysis methodologies and frameworks.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@capitec.co.za",
    "image": "pdf_images/22_Image105.jpg",
    "applyUrl": "https://toysruscareers.simplify.hr/Vacancy/181165"
  },
  {
    "id": 1015,
    "title": "Leadership and stakeholder management.",
    "company": "OUTsurance",
    "location": "Bloemfontein, South Africa Employment Type:  Full-time FAIS Role:",
    "salary": "Negotiable",
    "description": "\u2022 Process mapping, optimisation, and automation.\n\u2022 Continuous improvement and change management principles.\n\u2022 Root cause analysis and business case development.\n\u2022 Agile delivery methodologies and operational excellence.\nSkills\n\u2022 Strong analytical and problem -solving skills.\n\u2022 Excellent communication and presentation abilities.\n\u2022 Leadership and stakeholder management.\n\u2022 Project management and reporting skills.\n\u2022 Attention to detail and decision -making under pressure.\nConditions of Employment\n\u2022 Clear criminal and credit record.\nFore more information or to apply:\nhttps://careers.capitecbank.co.za/job/Johannesburg -Team -Leader -Operational -\nAnalytics -%28Operations -Delivery%29/1413756233/\nOUTsurance Broker \u2013 Bloemfontein\nLocation:  Bloemfontein, South Africa Employment Type:  Full-time FAIS Role:\nFinancial Advice Giving\nCompany Overview  For 28 years, OUTsurance  has been driving innovation in the\nSouth African insurance industry. As leaders in short -term insurance, we combine\ndigital solutions with human values to deliver exceptional service. Recognised as a\nTop Employer South Africa since 2022 , we pride ourselves on a vibrant, inclusive\nculture where employees thrive.\nWhat You Get OUT\n\u2022 Fuel card, company laptop, and cellphone.\n\u2022 Comprehensive 6 -week training program.\n\u2022 Career growth opportunities within OUTsurance.\n\u2022 Rewards and recognition programs.\n\u2022 Benefits: Medical aid, pension fund, group life, and disability cover.\n\u2022 Employee wellness programs (counselling, legal advice, financial coaching).\n\u2022 Volunteer opportunities through Staff Helping SA OUT .\nRole Overview  As an OUTsurance Broker , you will grow and develop the business\ninsurance portfolio by building a book of short -term insurance. You\u2019ll sell personal\nand commercial lines through prospecting, canvassing, and relationship\nmanagement.\nKey Competencies\n\u2022 Entrepreneurial mindset and self -starter attitude.\n\u2022 Strong business acumen and analytical skills.\n\u2022 Excellent communication and presentation abilities.\n\u2022 Relationship management and problem -solving skills.\n\u2022 Resilience, adaptability, and confidence under pressure.\nQualifications & Requirements\n\u2022 Matric / National Senior Certificate.\n\u2022 Valid Code B driver\u2019s license and reliable vehicle.\n\u2022 Minimum 3 years\u2019 external sales experience (face -to-face).",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@outsurance.co.za",
    "image": "pdf_images/24_Image112.jpg",
    "applyUrl": "https://careers.capitecbank.co.za/job/Johannesburg"
  },
  {
    "id": 1016,
    "title": "Additional Information  You will report directly to the Broker Regional Manager",
    "company": "OUTsurance",
    "location": "Cape Town, South Africa Employment Type:  Full-time FAIS Role:",
    "salary": "Negotiable",
    "description": "\u2022 Proven experience in lead generation, cold calling, and client relationship\nmanagement.\n\u2022 FAIS credits and RE5 certification (if previously appointed as a FAIS\nrepresentative).\nAdditional Information  You will report directly to the Broker Regional Manager\nand collaborate closely with the wider Commercial team. OUTsurance is committed\nto diversity, inclusion, and employment equity, welcoming applications from\ndesignated groups and persons with disabilities.\nFor more information or to apply:\nhttps://jobs.smartrecruiters.com/OUTsurance/744000135469569 -outsurance -broker -\nbloemfontein -\nOUTsurance Broker \u2013 Western Cape (Cape Town)\nLocation:  Cape Town, South Africa Employment Type:  Full-time FAIS Role:\nFinancial Advice Giving\nCompany Overview  For 28 years, OUTsurance  has been at the forefront of\ninnovation in the South African insurance industry. As leaders in short -term\ninsurance, we combine digital solutions with human values to deliver exceptional\nservice. Recognised as a Top Employer South Africa since 2022 , we pride\nourselves on a vibrant, inclusive culture where employees thrive.\nWhat You Get OUT\n\u2022 Fuel card, company laptop, and cellphone.\n\u2022 Comprehensive 6 -week training program.\n\u2022 Career growth opportunities within OUTsurance.\n\u2022 Rewards and recognition programs.\n\u2022 Benefits: Medical aid, pension fund, group life, and disability cover.\n\u2022 Employee wellness programs (counselling, legal advice, financial coaching).\n\u2022 Volunteer opportunities through Staff Helping SA OUT .\nRole Overview  As an OUTsurance Broker , you will grow and develop the business\ninsurance portfolio by building a book of short -term insurance. You\u2019ll sell personal\nand commercial lines through prospecting, canvassing, and relationship\nmanagement.\nKey Competencies\n\u2022 Entrepreneurial mindset and self -starter attitude.\n\u2022 Strong business acumen and analytical skills.\n\u2022 Excellent communication and presentation abilities.\n\u2022 Relationship management and problem -solving skills.\n\u2022 Resilience, adaptability, and confidence under pressure.\n\u2022 Creative flair and innovative thinking.\nQualifications & Requirements\n\u2022 Matric / National Senior Certificate.\n\u2022 Valid Code B driver\u2019s license and reliable vehicle.\n\u2022 Minimum 3 years\u2019 external sales experience (face -to-face).\n\u2022 Proven experience in lead generation, cold calling, and client relationship\nmanagement.\n\u2022 FAIS credits and RE5 certification (if previously appointed as a FAIS\nrepresentative).\nAdditional Information  You will report directly to the Broker Regional Manager\nand collaborate closely with the wider Commercial team. OUTsurance is committed\nto diversity, inclusion, and employment equity, welcoming applications from\ndesignated groups and persons with disabilities.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@outsurance.co.za",
    "image": "pdf_images/26_Image119.jpg",
    "applyUrl": "https://jobs.smartrecruiters.com/OUTsurance/744000135469569"
  },
  {
    "id": 1017,
    "title": "Client Care Advisor \u2013 Centurion",
    "company": "OUTsurance",
    "location": "Centurion, South Africa Employment Type:  Full-time FAIS Role:",
    "salary": "Negotiable",
    "description": "For more information or to apply:\nhttps://jobs.smartrecruiters.com/OUTsurance/744000134992116 -outsurance -broker -\nwestern -cape -\nClient Care Advisor \u2013 Centurion\nLocation:  Centurion, South Africa Employment Type:  Full-time FAIS Role:\nFinancial Advice Giving\nCompany Overview  For 28 years, OUTsurance  has been driving innovation in the\nSouth African insurance industry. Recognised as a Top Employer South Africa\nsince 2022 , we combine digital solutions with human values to deliver exceptional\nservice. Our people set the bar high with energy, expertise, and passion \u2014 making\nOUTsurance a great place to grow your career.\nWhat You Get OUT\n\u2022 Fun, inclusive company culture that embraces diversity.\n\u2022 Rewards and recognition programs.\n\u2022 Benefits: Medical aid, pension fund, group life, and disability cover.\n\u2022 Growth opportunities through internal promotions.\n\u2022 Employee wellness programs (counselling, legal advice, financial coaching).\n\u2022 Central office location with shuttles to Gautrain and taxi rank.\n\u2022 Onsite facilities: clinic, canteen, carwash, barber, beauty salon, sports\nfacilities, daycare centre, maternity rooms, and prayer rooms.\n\u2022 Casual dress code and supportive team environment.\nRole Overview  As a Client Care Advisor , you will upsell existing clients and service\nincoming calls within the Client Care Department. The role requires attention to\ndetail, professionalism, and efficiency in handling client queries and complaints,\nensuring a positive customer experience.\nKey Responsibilities\n\u2022 Upsell existing policies and provide excellent client service.\n\u2022 Handle client queries and complaints professionally.\n\u2022 Deliver on sales and retention targets.\n\u2022 Align personal work values with OUTsurance\u2019s values: Awesome Service,\nDynamic, Honest, Human, Passionate, and Recognition.\nQualifications & Requirements\n\u2022 Matric / National Senior Certificate.\n\u2022 FAIS accreditation essential (RE5 and full qualification for applicants\nappointed before December 2010).\n\u2022 Extensive sales and customer service experience.\n\u2022 Previous call centre experience in a client -centric or sales environment\npreferred.\nCompetencies & Attributes\n\u2022 Resilience and adaptability under pressure.\n\u2022 Strong selling, negotiation, and influencing skills.\n\u2022 Excellent interpersonal and communication abilities.\n\u2022 Attention to detail and results -driven mindset.\n\u2022 Team player with initiative and integrity.\n\u2022 Highly motivated, ambitious, and customer -focused.\nEmployment Equity  OUTsurance is committed to fostering an inclusive and diverse\nworkplace. Preference will be given to candidates from designated groups and\npersons with disabilities who meet the role requirements.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@outsurance.co.za",
    "image": "pdf_images/28_Image126.jpg",
    "applyUrl": "https://jobs.smartrecruiters.com/OUTsurance/744000134992116"
  },
  {
    "id": 1018,
    "title": "Executive: Corporate Development",
    "company": "OUTsurance",
    "location": "Head Office, South Africa Closing Date:  12 July 2026 Department:",
    "salary": "Negotiable",
    "description": "For more information or to apply:\nhttps://jobs.smartrecruiters.com/OUTsurance/744000135685195 -client -care-advisor\nExecutive: Corporate Development\nLocation:  Head Office, South Africa Closing Date:  12 July 2026 Department:\nCorporate Development Industry:  Mining & Refining Experience Level:  Executive\nAbout Impala Platinum  Impala Platinum is a leading mining and refining company\ncommitted to innovation, safety, and sustainability. We value diversity and inclusion\nand strive to create a workplace where everyone can thrive.\nPurpose of the Role  The Executive: Corporate Development  will lead and\nadvance the Group\u2019s corporate development agenda through rigorous analysis,\nstrategic insight, and disciplined execution of transactions and initiatives. The role\nfocuses on portfolio optimisation, growth strategy, capital allocation, and st rategic\ninvestment decision -making, ensuring alignment with Group strategy and\ngovernance frameworks.\nMinimum Qualifications & Requirements\n\u2022 NQF Level 7 qualification in Business, Commerce, Mining, or related\ndiscipline.\n\u2022 Post-graduate qualification (MBA, CFA) advantageous.\n\u2022 10\u201315 years\u2019 experience in Corporate Development, M&A, Investment\nBanking, or advisory (mining experience required).\n\u2022 Proven track record in transaction origination, negotiation, due diligence, and\nvaluation.\n\u2022 Advanced financial modelling and valuation skills.\n\u2022 Strong knowledge of corporate strategy, capital allocation, and growth\nframeworks.\n\u2022 Excellent analytical, problem -solving, and strategic thinking ability.\n\u2022 Strong interpersonal, emotional intelligence, and communication skills.\n\u2022 Experience leading cross -functional teams and delivering on deadlines.\nKey Responsibilities\n\u2022 Lead corporate development activities across the Implats Group, including\norigination, evaluation, due diligence, valuation, negotiation, and execution.\n\u2022 Identify and prioritise acquisitions, partnerships, and growth opportunities.\n\u2022 Manage all aspects of transaction processes, from sourcing to execution.\n\u2022 Integrate market insights, industry trends, and competitive dynamics into\nstrategic investment pipelines.\n\u2022 Provide strategic analysis and insights to support Exco and Board\ndecision -making.\n\u2022 Build and maintain financial models for corporate development and growth\ninitiatives.\n\u2022 Prepare clear, actionable documentation for Board, Exco, and external\nstakeholders.\n\u2022 Ensure compliance with governance, risk management, and regulatory\nframeworks.\n\u2022 Engage and influence senior stakeholders, including Exco, Board, investors,\nand advisors.\n\u2022 Drive cross -functional collaboration to deliver on strategic priorities.\nApplication Process  Applications (CV, copies of qualifications, and ID) must be\nuploaded via the vacancy portal:\n\u2022 Internal candidates: Intranet \u2192 Head Office \u2192 Vacancies \u2192 Let\u2019s Talk.\n\u2022 External candidates: Visit www.implats.co.za  under Careers and apply online.\nAdditional Information",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@outsurance.co.za",
    "image": "pdf_images/30_Image132.jpg",
    "applyUrl": "https://jobs.smartrecruiters.com/OUTsurance/744000135685195"
  },
  {
    "id": 1019,
    "title": "Corporate Development Manager (D4)",
    "company": "Impala Platinum",
    "location": "Head Office, South Africa Closing Date:  12 July 2026 Department:",
    "salary": "Negotiable",
    "description": "\u2022 Shortlisted candidates may undergo psychometric assessments.\n\u2022 If you do not hear from HR within 30 days after the closing date, consider your\napplication unsuccessful.\n\u2022 Preference will be given to candidates from designated groups in line with the\nEmployment Equity Act and the company\u2019s recruitment policy.\nFor more information or to apply: https://www.careers -\npage.com/implats/job/4R67R447\nCorporate Development Manager (D4)\nLocation:  Head Office, South Africa Closing Date:  12 July 2026 Department:\nCorporate Development Industry:  Mining & Refining Experience Level:  Manager\nAbout Impala Platinum  Impala Platinum is a leading mining and refining company\ncommitted to innovation, safety, and sustainability. We value diversity and inclusion\nand strive to create a workplace where everyone can thrive.\nPurpose of the Role  The Corporate Development Manager  will provide\nend-to-end support to the Executive: Corporate Development and the wider function\nin identifying, assessing, sourcing, and implementing corporate development\ninitiatives. These include acquisitions, divestitures, partnerships, and strategic\nprojects aimed at deli vering long -term value to the Group. The role assumes primary\nresponsibility for financial modelling, valuation, and due diligence processes to\nsupport strategic decision -making and investment execution.\nMinimum Qualifications & Requirements\n\u2022 NQF Level 7 qualification in Business, Commerce, Mining, or related\ndiscipline.\n\u2022 6\u20138 years\u2019 experience in mining corporate/business development, investment\nbanking, corporate finance, or advisory.\n\u2022 Proven experience in executing M&A and corporate finance transactions, with\nknowledge of regulatory frameworks.\n\u2022 Strong financial modelling and valuation expertise.\n\u2022 Knowledge of commodities/mining industry and market dynamics.\n\u2022 Excellent analytical, problem -solving, and strategic thinking skills.\n\u2022 Strong communication, presentation, and writing ability.\n\u2022 Self-starter with adaptability in fast -paced environments.\n\u2022 Strong organisational skills with ability to manage multiple projects.\nKey Responsibilities\n\u2022 Assist in identifying and assessing corporate development opportunities\n(M&A, partnerships, growth initiatives).\n\u2022 Develop, review, and maintain robust financial and valuation models.\n\u2022 Provide commercial analysis and valuation insights across the Group.\n\u2022 Analyse industry trends, competitor activity, and market developments.\n\u2022 Support execution of corporate transactions and manage projects as required.\n\u2022 Coordinate due diligence processes with internal and external stakeholders.\n\u2022 Prepare detailed valuation analyses, investment cases, and financial insights.\n\u2022 Compile and deliver high -quality Board and Exco papers, reports, and\npresentations.\n\u2022 Collaborate with advisors and cross -functional teams to ensure successful\noutcomes.\nApplication Process  Applications (CV, copies of qualifications, and ID) must be\nuploaded via the vacancy portal:\n\u2022 Internal candidates: Intranet \u2192 Head Office \u2192 Vacancies \u2192 Let\u2019s Talk.\n\u2022 External candidates: Visit www.implats.co.za  under Careers and apply online.\nAdditional Information",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@impalaplatinum.co.za",
    "image": "pdf_images/32_Image33.jpg",
    "applyUrl": "https://www.careers"
  },
  {
    "id": 1020,
    "title": "Maintenance Specialist",
    "company": "Sasol",
    "location": "Germiston,",
    "salary": "Negotiable",
    "description": "\u2022 Shortlisted candidates may undergo psychometric assessments.\n\u2022 If you do not hear from HR within 30 days after the closing date, consider your\napplication unsuccessful.\n\u2022 Preference will be given to candidates from designated groups in line with the\nEmployment Equity Act and the company\u2019s recruitment policy.\nFor mo re information or to apply: https://www.careers -\npage.com/implats/job/5W97W8X3\nMaintenance Specialist\nPosting Date:  1 July 2026 Closing Date:  14 July 2026 Location:  Germiston,\nGauteng (Extensive travel required) Company:  Sasol Job Requisition ID:  12638\nOME:  MSA \u2013 Energy Marketing & Sales\nAbout Sasol  Sasol is a global integrated chemicals and energy company with a\n75-year heritage. We use our expertise and technologies to safely and sustainably\nsource, manufacture, and market chemical and energy products worldwide. At Sasol,\npeople are at the centre o f everything we do, and we invest in employee\ndevelopment at every stage of the career journey.\nPurpose of the Role  Provide maintenance management support to Sasol\u2019s\nCommercial and Retail businesses by managing the Facility Management Company\n(FMC) to deliver planning, implementation, and control of maintenance activities.\nEnsure asset optimisation through best practic e maintenance, compliance with\nsafety regulations, and effective stakeholder engagement.\nKey Accountabilities\n\u2022 Own successful maintenance implementation across Commercial and Retail\nbusinesses.\n\u2022 Develop and implement maintenance strategies and preventative schedules.\n\u2022 Identify, analyse, and mitigate risks to acceptable levels.\n\u2022 Ensure compliance with SHE, quality, cost, and schedule requirements.\n\u2022 Maintain inspection records in SAP and hard copy where required.\n\u2022 Manage FMC relationships to ensure SLA compliance and timely resolution of\nopen calls.\n\u2022 Investigate and resolve customer complaints related to engineering activities.\n\u2022 Oversee contractors and consultants for remediation of contaminated sites.\n\u2022 Ensure adherence to legal, statutory, and environmental regulations.\n\u2022 Conduct audits to monitor compliance with safety programmes (KUEs, Life\nSaving Behaviours, PTRA).\n\u2022 Evaluate contracts and approve FMC quotes in line with technical outputs.\n\u2022 Review FMC performance reports and conduct site visits.\n\u2022 Provide input into updates of SANS codes, internal specifications, and\nprocedures.\n\u2022 Contribute to annual and long -term maintenance budgets and cost control.\nFormal Education\n\u2022 Bachelor\u2019s degree in Mechanical or Electrical Engineering (or equivalent).\nExperience\n\u2022 Minimum 6 years relevant experience.\nLicense\n\u2022 Valid Code B driver\u2019s license.\nSkills & Competencies\n\u2022 Collaboration and communication.\n\u2022 Troubleshooting technical issues.\n\u2022 Engineering design and equipment utilisation.",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@sasol.co.za",
    "image": "pdf_images/34_Image147.jpg",
    "applyUrl": "https://www.careers"
  },
  {
    "id": 1021,
    "title": "Specialist/1410262433/",
    "company": "Sasol",
    "location": "Secunda,",
    "salary": "Negotiable",
    "description": "\u2022 Planning, organisation, and accountability.\n\u2022 Decision -making and problem -solving.\nEmployment Equity  Sasol is an equal opportunity and affirmative action employer.\nPreference will be given to applicants from designated groups and persons with\ndisabilities, in line with Sasol\u2019s Employment Equity Plan.\nNote  If you do not hear from Sasol within 60 days of the closing date, please\nconsider your application unsuccessful.\nFor more information or to apply: https://jobs.sasol.com/job/Sandton -Maintenance -\nSpecialist/1410262433/\nJunior Chemical Plant Operator (Jnr CPO)\nPosting Date:  2 July 2026 Closing Date:  16 July 2026 Location:  Secunda,\nMpumalanga Company:  Sasol Job Requisition ID:  12619 OME:  OPP \u2013 Secunda\nOperations\nAbout Sasol  Sasol is a global integrated chemicals and energy company with a\n75-year heritage. We use our expertise and technologies to safely and sustainably\nsource, manufacture, and market chemical and energy products worldwide. At Sasol,\npeople are at the centre of everything we do, and we invest in employee\ndevelopment at every st age of the career journey.\nPurpose of the Role  Coordinate and direct maintenance and repair services for a\nspecific process within a production line, through control panel management and\nadvanced troubleshooting.\nKey Accountabilities\n\u2022 Provide feedback to supervisors on work progress.\n\u2022 Participate in risk assessments to improve safety.\n\u2022 Maintain good housekeeping and adhere to waste disposal procedures.\n\u2022 Work independently and understand business KPIs.\n\u2022 Apply and maintain safety standards in the working environment.\n\u2022 Participate in shift handovers and toolbox talks.\n\u2022 Identify personal training needs and incorporate into PDP .\n\u2022 Coach learners and present on specific plant equipment.\n\u2022 Conduct IMS inspections to improve plant sustainability.\n\u2022 Play a key role during emergency situations to restore plant operations.\n\u2022 Collaborate effectively with team members and other disciplines.\nFormal Education\n\u2022 Matric/N3 with Maths, English, and Physical Science.\n\u2022 CHIETA NQF Level 2, or\n\u2022 Chemical Plant Operator Occupational Qualification (CPO EISA).\nExperience\n\u2022 Minimum 2 years relevant experience.\nLicense\n\u2022 Valid driver\u2019s license (Code B).\nSkills & Competencies\n\u2022 Optimises work processes and drives results.\n\u2022 Effective communication and collaboration.\n\u2022 Troubleshooting and equipment utilisation.\n\u2022 Production resource and risk management.\n\u2022 Planning, organisation, and accountability.\nEmployment Equity  Sasol is an equal opportunity and affirmative action employer.\nPreference will be given to applicants from designated groups and persons with\ndisabilities, in line with Sasol\u2019s Employment Equity Plan.\nNote  If you do not hear from Sasol within 60 days of the closing date, please\nconsider your application unsuccessful.\nFor more information or to apply: https://jobs.sasol.com/job/Secunda -Junior -\nChemical -Plant -Operator -%28Jnr -CPO%29/1410924533/",
    "jobType": "full-time",
    "workLocation": "on-site",
    "salaryRange": "mid",
    "postedDate": "Jul 2026",
    "contactEmail": "careers@sasol.co.za",
    "image": "pdf_images/36_Image154.jpg",
    "applyUrl": "https://jobs.sasol.com/job/Sandton"
  }
];
